config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :instances

  root 'instances#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instance.rb
class Instance < ApplicationRecord
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  before_action :set_instance, only: [:show, :edit, :update, :destroy]

  # GET /instances
  def index
    @instances = Instance.all
  end

  # GET /instances/new
  def new
    @instances = Instance.new
  end

  # GET /instances/1
  def show
  end

  # GET /instances/1/edit
  def edit
  end

  # POST /instances
  def create
    @instance = Instance.new(micropost_params)

    respond_to do |format|
      @instance.save
      format.html {redirect_to @instance, notice: 'Instance Created.'}
    end
  end

  def update
    respond_to do |format|
      @instance.update(micropost_params)
      format.html{ redirect_to "/", notice: 'Instance Updated'}
    end
  end

  # DELETE /instances/1
  # DELETE /instances/1.json
  def destroy
    respond_to do |format|
      @instance.destroy
      format.html{ redirect_to "/", notice: 'Instance Delete'}
    end
  end

  private

    def set_instance
      @instance = Instance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:instance).permit(:id, :name, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def form_with_source(&block)
    form_html = capture(&block)

    content_tag(:div, class: "example") do
      codemirror = content_tag(:div, class: "code", style: "display: none") do
        content_tag(:textarea, class: "codemirror") do
          HtmlBeautifier.beautify(form_html.strip.gsub(">", ">\n").gsub("<", "\n<"))
        end
      end

      toggle = content_tag(:button, class: "toggle btn btn-sm btn-info") do
        "Show Source Code"
      end

      concat(form_html)
      concat(toggle)
      concat(codemirror)
    end
  end
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/_form.html.erb
<%= form_with(model: instance, local: true) do |form| %>
  <% if instance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/instances/edit.erb
<%= bootstrap_form_for(@instance, layout: :horizontal) do |f| %>
  <%= f.text_field :name, label: "Name" %>
  <%= f.text_field :description, label: "Description" %>
  <%= f.submit "Update Instance" %>
<% end %>

app/views/instances/index.html.erb
<p id="notice"><%= notice %></p>

<%= button_to "New Instance", new_instance_path, :id => "open-contacts-dialog-btn",
              :class => "btn btn-outline-success my-2 my-sm-0", :method => :get %>


<div class="table-responsive">
  <table class="table table-bordered">
    <tbody>
    <% [*@instances].each do |instance| %>
      <tr>
        <td><%= link_to instance.name, instance %></td>
        <td width="20"><%= link_to 'Edit', edit_instance_url(instance) %></td>
        <td width="20"><%= link_to 'Destroy', instance, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>

    </tbody>
  </table>
</div>

app/views/instances/new.erb
<!--<h1>Create new instance</h1>-->
  <%= bootstrap_form_for @instances, url: "/instances", layout: :horizontal do |form| %>
    <%= form.text_field :name, label: "Name" %>
    <%= form.text_field :description, label: "Description" %>

    <%= form.submit %>
  <% end %>

app/views/instances/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @instance.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @instance.description %>
</p>

<%= link_to 'Back to main page', instances_path %> |
<%= link_to 'Edit', edit_instance_path(@instance) %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.33.0/codemirror.min.css">

  <style type="text/css">
    .example {
      padding: 1.5em;
      border: .2rem solid #f7f7f9;
      margin-bottom: 3em;
    }

    form {
      margin-bottom: 1.5em;
    }

    .CodeMirror {
      border: 1px solid #eee;
      height: auto;
    }

    .rails-bootstrap-forms-datetime-select select {
      display: inline-block;
      width: auto;
    }

    .header {
      box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, .05), inset 0 -1px 0 rgba(0, 0, 0, .1);
    }

    .sidebar {
      border-right: 1px solid rgba(0, 0, 0, .1);
      height: calc(100vh);
      background: #031b4d;
    }

    .navbar {
      padding-top: 1rem;
      padding-bottom: 1rem;
    }

    .main {
      padding-top: 1rem;
      padding-bottom: 1rem;
      padding-left: 1em;
      padding-right: 1em;
      width: 75%;
    }

    .bd-toc-link {
      display: block;
      /*padding: .25rem 1.5rem;*/
      font-weight: 500;
      color: white;
    }

    .bd-toc-link a {
      color: white;
    }

    .logo {
      padding-top: 20px;
      font-size: 25px;
      color: #677694;
    }

    .table-bordered td {
      border: 0px !important;
    }

    .table-bordered tr {
      border: 1px solid #dee2e6 !important;
    }

    @media (min-width: 768px) {
      .col-md-3 {
        flex: 0 0 25%;
        max-width: 20% !important;
      }
    }

  </style>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <title>VPS Manager</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>

<body>
<!--<header class="navbar navbar-expand navbar-dark flex-column flex-md-row bd-navbar header">-->
<!--  <h1>VPS Manager</h1>-->
<!--</header>-->

<div id="main-container" class="container-fluid">
  <div class="row">
    <div id="sidebar" class="col-12 col-md-3 col-xl-2 sidebar">
      <h1 class="logo">VPS Manager</h1>
      <nav id="sidebar" class="navbar">
        <ul class="list-unstyled components">
          <li class="bd-toc-link"><%= link_to 'Instances', instances_path %></li>
        </ul>
      </nav>
    </div>
    <div id="content" class="col-xs-9 main">
      <%= yield %>
    </div>
  </div>
</div>

<!-- Optional JavaScript-->
<!-- jQuery first, then Popper.js, then Bootstrap JS-->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.33.0/codemirror.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.33.0/mode/htmlmixed/htmlmixed.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.33.0/mode/xml/xml.min.js"></script>

<script type="text/javascript">
    $(document).on("click", "button.toggle", function () {
        var example = $(this).parent(".example");
        $(this).hide();
        $(".code", example).show()
        CodeMirror.fromTextArea($("textarea.codemirror", example)[0], {
            mode: "htmlmixed",
            tabSize: 2,
            lineNumbers: true,
            viewportMargin: Infinity
        })
    });
</script>
</body>
</html>